// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: rag/v1/rag.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_SERVING_STATUS_UNSPECIFIED HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING_STATUS_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_SERVING_STATUS_NOT_SERVING HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVING_STATUS_DEGRADED    HealthCheckResponse_ServingStatus = 3
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNSPECIFIED",
		1: "SERVING_STATUS_SERVING",
		2: "SERVING_STATUS_NOT_SERVING",
		3: "SERVING_STATUS_DEGRADED",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNSPECIFIED": 0,
		"SERVING_STATUS_SERVING":     1,
		"SERVING_STATUS_NOT_SERVING": 2,
		"SERVING_STATUS_DEGRADED":    3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rag_v1_rag_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_rag_v1_rag_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{1, 0}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=rag.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_SERVING_STATUS_UNSPECIFIED
}

type InspectFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FileType      string                 `protobuf:"bytes,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	HeaderBytes   []byte                 `protobuf:"bytes,3,opt,name=header_bytes,json=headerBytes,proto3" json:"header_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectFileRequest) Reset() {
	*x = InspectFileRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectFileRequest) ProtoMessage() {}

func (x *InspectFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectFileRequest.ProtoReflect.Descriptor instead.
func (*InspectFileRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *InspectFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *InspectFileRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *InspectFileRequest) GetHeaderBytes() []byte {
	if x != nil {
		return x.HeaderBytes
	}
	return nil
}

type InspectFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectFileResponse) Reset() {
	*x = InspectFileResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectFileResponse) ProtoMessage() {}

func (x *InspectFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectFileResponse.ProtoReflect.Descriptor instead.
func (*InspectFileResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{3}
}

func (x *InspectFileResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *InspectFileResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_rag_v1_rag_proto protoreflect.FileDescriptor

const file_rag_v1_rag_proto_rawDesc = "" +
	"\n" +
	"\x10rag/v1/rag.proto\x12\x06rag.v1\"\x14\n" +
	"\x12HealthCheckRequest\"\xe3\x01\n" +
	"\x13HealthCheckResponse\x12A\n" +
	"\x06status\x18\x01 \x01(\x0e2).rag.v1.HealthCheckResponse.ServingStatusR\x06status\"\x88\x01\n" +
	"\rServingStatus\x12\x1e\n" +
	"\x1aSERVING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVING_STATUS_SERVING\x10\x01\x12\x1e\n" +
	"\x1aSERVING_STATUS_NOT_SERVING\x10\x02\x12\x1b\n" +
	"\x17SERVING_STATUS_DEGRADED\x10\x03\"p\n" +
	"\x12InspectFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_type\x18\x02 \x01(\tR\bfileType\x12!\n" +
	"\fheader_bytes\x18\x03 \x01(\fR\vheaderBytes\"M\n" +
	"\x13InspectFileResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription2\x9c\x01\n" +
	"\n" +
	"RagService\x12F\n" +
	"\vHealthCheck\x12\x1a.rag.v1.HealthCheckRequest\x1a\x1b.rag.v1.HealthCheckResponse\x12F\n" +
	"\vInspectFile\x12\x1a.rag.v1.InspectFileRequest\x1a\x1b.rag.v1.InspectFileResponseB\x1fZ\x1dgateway/internal/proto/rag/v1b\x06proto3"

var (
	file_rag_v1_rag_proto_rawDescOnce sync.Once
	file_rag_v1_rag_proto_rawDescData []byte
)

func file_rag_v1_rag_proto_rawDescGZIP() []byte {
	file_rag_v1_rag_proto_rawDescOnce.Do(func() {
		file_rag_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)))
	})
	return file_rag_v1_rag_proto_rawDescData
}

var file_rag_v1_rag_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rag_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rag_v1_rag_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: rag.v1.HealthCheckResponse.ServingStatus
	(*HealthCheckRequest)(nil),             // 1: rag.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 2: rag.v1.HealthCheckResponse
	(*InspectFileRequest)(nil),             // 3: rag.v1.InspectFileRequest
	(*InspectFileResponse)(nil),            // 4: rag.v1.InspectFileResponse
}
var file_rag_v1_rag_proto_depIdxs = []int32{
	0, // 0: rag.v1.HealthCheckResponse.status:type_name -> rag.v1.HealthCheckResponse.ServingStatus
	1, // 1: rag.v1.RagService.HealthCheck:input_type -> rag.v1.HealthCheckRequest
	3, // 2: rag.v1.RagService.InspectFile:input_type -> rag.v1.InspectFileRequest
	2, // 3: rag.v1.RagService.HealthCheck:output_type -> rag.v1.HealthCheckResponse
	4, // 4: rag.v1.RagService.InspectFile:output_type -> rag.v1.InspectFileResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rag_v1_rag_proto_init() }
func file_rag_v1_rag_proto_init() {
	if File_rag_v1_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_v1_rag_proto_goTypes,
		DependencyIndexes: file_rag_v1_rag_proto_depIdxs,
		EnumInfos:         file_rag_v1_rag_proto_enumTypes,
		MessageInfos:      file_rag_v1_rag_proto_msgTypes,
	}.Build()
	File_rag_v1_rag_proto = out.File
	file_rag_v1_rag_proto_goTypes = nil
	file_rag_v1_rag_proto_depIdxs = nil
}
